
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.monster
{
public sealed partial class MonsterDeck : Luban.BeanBase
{
    public MonsterDeck(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MonsterId = _buf.ReadInt();
        MonsterId_Ref = null;
        Order = _buf.ReadInt();
        CardId = _buf.ReadInt();
        CardId_Ref = null;
        Count = _buf.ReadInt();
        Comment = _buf.ReadString();
    }

    public static MonsterDeck DeserializeMonsterDeck(ByteBuf _buf)
    {
        return new monster.MonsterDeck(_buf);
    }

    /// <summary>
    /// 记录标识
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 怪物标识
    /// </summary>
    public readonly int MonsterId;
    public monster.Monster MonsterId_Ref;
    /// <summary>
    /// 剧本顺序
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 卡牌标识
    /// </summary>
    public readonly int CardId;
    public card.Card CardId_Ref;
    /// <summary>
    /// 份数
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = -171578513;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        MonsterId_Ref = tables.TbMonster.GetOrDefault(MonsterId);
        CardId_Ref = tables.TbCard.GetOrDefault(CardId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "monsterId:" + MonsterId + ","
        + "order:" + Order + ","
        + "cardId:" + CardId + ","
        + "count:" + Count + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

