
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.monster
{
public sealed partial class Monster : Luban.BeanBase
{
    public Monster(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        AssetId = _buf.ReadString();
    }

    public static Monster DeserializeMonster(ByteBuf _buf)
    {
        return new monster.Monster(_buf);
    }

    /// <summary>
    /// 怪物标识
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 怪物名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 怪物描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 资源标识
    /// </summary>
    public readonly string AssetId;
   
    public const int __ID__ = 1495842214;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "assetId:" + AssetId + ","
        + "}";
    }
}
}

