
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.monster
{
public sealed partial class MonsterIntent : Luban.BeanBase
{
    public MonsterIntent(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MonsterId = _buf.ReadInt();
        Order = _buf.ReadInt();
        IntentType = (monster.MonsterIntentType)_buf.ReadInt();
        Value = _buf.ReadInt();
        Weight = _buf.ReadInt();
        Comment = _buf.ReadString();
    }

    public static MonsterIntent DeserializeMonsterIntent(ByteBuf _buf)
    {
        return new monster.MonsterIntent(_buf);
    }

    /// <summary>
    /// 意图标识
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 怪物标识
    /// </summary>
    public readonly int MonsterId;
    /// <summary>
    /// 序列顺序（&gt;0时使用序列循环）
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 意图类型
    /// </summary>
    public readonly monster.MonsterIntentType IntentType;
    /// <summary>
    /// 意图数值
    /// </summary>
    public readonly int Value;
    /// <summary>
    /// 权重（&gt;0时使用权重随机）
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = -1526232094;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "monsterId:" + MonsterId + ","
        + "order:" + Order + ","
        + "intentType:" + IntentType + ","
        + "value:" + Value + ","
        + "weight:" + Weight + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

