
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.monster
{ 
    public enum MonsterIntentType
    {
        /// <summary>
        /// 攻击意图
        /// </summary>
        Attack = 1,
        /// <summary>
        /// 防御意图
        /// </summary>
        Defend = 2,
        /// <summary>
        /// 增益意图
        /// </summary>
        Buff = 3,
        /// <summary>
        /// 减益意图
        /// </summary>
        Debuff = 4,
    }

} 

