
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.monster
{
/// <summary>
/// 怪物意图配置表
/// </summary>
public partial class TbMonsterIntent
{
    private readonly System.Collections.Generic.Dictionary<int, monster.MonsterIntent> _dataMap;
    private readonly System.Collections.Generic.List<monster.MonsterIntent> _dataList;
    
    public TbMonsterIntent(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, monster.MonsterIntent>(n);
        _dataList = new System.Collections.Generic.List<monster.MonsterIntent>(n);
        for(int i = n ; i > 0 ; --i)
        {
            monster.MonsterIntent _v;
            _v = global::GameConfig.monster.MonsterIntent.DeserializeMonsterIntent(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, monster.MonsterIntent> DataMap => _dataMap;
    public System.Collections.Generic.List<monster.MonsterIntent> DataList => _dataList;

    public monster.MonsterIntent GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public monster.MonsterIntent Get(int key) => _dataMap[key];
    public monster.MonsterIntent this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

