
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.monster
{
/// <summary>
/// 怪物配置表
/// </summary>
public partial class TbMonster
{
    private readonly System.Collections.Generic.Dictionary<string, monster.Monster> _dataMap;
    private readonly System.Collections.Generic.List<monster.Monster> _dataList;
    
    public TbMonster(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, monster.Monster>(n);
        _dataList = new System.Collections.Generic.List<monster.Monster>(n);
        for(int i = n ; i > 0 ; --i)
        {
            monster.Monster _v;
            _v = global::GameConfig.monster.Monster.DeserializeMonster(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, monster.Monster> DataMap => _dataMap;
    public System.Collections.Generic.List<monster.Monster> DataList => _dataList;

    public monster.Monster GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public monster.Monster Get(string key) => _dataMap[key];
    public monster.Monster this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

