
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.monster
{
/// <summary>
/// 怪物牌组配置表
/// </summary>
public partial class TbMonsterDeck
{
    private readonly System.Collections.Generic.Dictionary<int, monster.MonsterDeck> _dataMap;
    private readonly System.Collections.Generic.List<monster.MonsterDeck> _dataList;
    
    public TbMonsterDeck(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, monster.MonsterDeck>(n);
        _dataList = new System.Collections.Generic.List<monster.MonsterDeck>(n);
        for(int i = n ; i > 0 ; --i)
        {
            monster.MonsterDeck _v;
            _v = global::GameConfig.monster.MonsterDeck.DeserializeMonsterDeck(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, monster.MonsterDeck> DataMap => _dataMap;
    public System.Collections.Generic.List<monster.MonsterDeck> DataList => _dataList;

    public monster.MonsterDeck GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public monster.MonsterDeck Get(int key) => _dataMap[key];
    public monster.MonsterDeck this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

