
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
public sealed partial class LevelWave : Luban.BeanBase
{
    public LevelWave(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        LevelId_Ref = null;
        Order = _buf.ReadInt();
        Type = (level.WaveType)_buf.ReadInt();
        Title = _buf.ReadString();
        Desc = _buf.ReadString();
        ContinueText = _buf.ReadString();
        if(_buf.ReadBool()){ PayloadId = _buf.ReadInt(); } else { PayloadId = null; }
    }

    public static LevelWave DeserializeLevelWave(ByteBuf _buf)
    {
        return new level.LevelWave(_buf);
    }

    /// <summary>
    /// 波次标识
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属关卡标识
    /// </summary>
    public readonly int LevelId;
    public level.Level LevelId_Ref;
    /// <summary>
    /// 波次顺序
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 波次类型
    /// </summary>
    public readonly level.WaveType Type;
    /// <summary>
    /// 波次标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 波次描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 继续文案
    /// </summary>
    public readonly string ContinueText;
    /// <summary>
    /// 可选负载标识
    /// </summary>
    public readonly int? PayloadId;
   
    public const int __ID__ = -923420013;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        LevelId_Ref = tables.TbLevel.GetOrDefault(LevelId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "order:" + Order + ","
        + "type:" + Type + ","
        + "title:" + Title + ","
        + "desc:" + Desc + ","
        + "continueText:" + ContinueText + ","
        + "payloadId:" + PayloadId + ","
        + "}";
    }
}
}

