
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
public sealed partial class Level : Luban.BeanBase
{
    public Level(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        IsDefault = _buf.ReadBool();
        {int n0 = _buf.ReadSize(); WaveIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); WaveIds.Add(_e0);}}
    }

    public static Level DeserializeLevel(ByteBuf _buf)
    {
        return new level.Level(_buf);
    }

    /// <summary>
    /// 关卡标识
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 关卡名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 关卡描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 默认入口标记
    /// </summary>
    public readonly bool IsDefault;
    /// <summary>
    /// 波次标识列表
    /// </summary>
    public readonly System.Collections.Generic.List<string> WaveIds;
   
    public const int __ID__ = 685080698;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "isDefault:" + IsDefault + ","
        + "waveIds:" + Luban.StringUtil.CollectionToString(WaveIds) + ","
        + "}";
    }
}
}

