
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
/// <summary>
/// 关卡波次表
/// </summary>
public partial class TbLevelWave
{
    private readonly System.Collections.Generic.Dictionary<string, level.LevelWave> _dataMap;
    private readonly System.Collections.Generic.List<level.LevelWave> _dataList;
    
    public TbLevelWave(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, level.LevelWave>(n);
        _dataList = new System.Collections.Generic.List<level.LevelWave>(n);
        for(int i = n ; i > 0 ; --i)
        {
            level.LevelWave _v;
            _v = global::GameConfig.level.LevelWave.DeserializeLevelWave(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, level.LevelWave> DataMap => _dataMap;
    public System.Collections.Generic.List<level.LevelWave> DataList => _dataList;

    public level.LevelWave GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public level.LevelWave Get(string key) => _dataMap[key];
    public level.LevelWave this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

