
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
/// <summary>
/// 关卡主表
/// </summary>
public partial class TbLevel
{
    private readonly System.Collections.Generic.Dictionary<int, level.Level> _dataMap;
    private readonly System.Collections.Generic.List<level.Level> _dataList;
    
    public TbLevel(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, level.Level>(n);
        _dataList = new System.Collections.Generic.List<level.Level>(n);
        for(int i = n ; i > 0 ; --i)
        {
            level.Level _v;
            _v = global::GameConfig.level.Level.DeserializeLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, level.Level> DataMap => _dataMap;
    public System.Collections.Generic.List<level.Level> DataList => _dataList;

    public level.Level GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public level.Level Get(int key) => _dataMap[key];
    public level.Level this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

