
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.level
{ 
    public enum WaveType
    {
        /// <summary>
        /// 战斗波次
        /// </summary>
        Battle = 1,
        /// <summary>
        /// 宝箱波次
        /// </summary>
        Chest = 2,
        /// <summary>
        /// 商店波次
        /// </summary>
        Shop = 3,
    }

} 

