
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.card
{ 
    public enum CardReleaseKind
    {
        /// <summary>
        /// 近战释放类型
        /// </summary>
        Melee = 1,
        /// <summary>
        /// 投射释放类型
        /// </summary>
        Projectile = 2,
        /// <summary>
        /// 法术或技能释放类型
        /// </summary>
        Spell = 3,
    }

} 

