
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.card
{
public sealed partial class Card : Luban.BeanBase
{
    public Card(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Cost = _buf.ReadInt();
        OwnerKind = (card.OwnerKind)_buf.ReadInt();
        TargetMode = (card.TargetMode)_buf.ReadInt();
        IsBasic = _buf.ReadBool();
        AssetId = _buf.ReadString();
    }

    public static Card DeserializeCard(ByteBuf _buf)
    {
        return new card.Card(_buf);
    }

    /// <summary>
    /// 卡牌标识
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 卡牌名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 卡牌描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 能量消耗
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 卡牌归属
    /// </summary>
    public readonly card.OwnerKind OwnerKind;
    /// <summary>
    /// 目标模式
    /// </summary>
    public readonly card.TargetMode TargetMode;
    /// <summary>
    /// 基础卡牌标记
    /// </summary>
    public readonly bool IsBasic;
    /// <summary>
    /// 资源标识
    /// </summary>
    public readonly string AssetId;
   
    public const int __ID__ = -291760306;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "cost:" + Cost + ","
        + "ownerKind:" + OwnerKind + ","
        + "targetMode:" + TargetMode + ","
        + "isBasic:" + IsBasic + ","
        + "assetId:" + AssetId + ","
        + "}";
    }
}
}

