
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.card
{
public sealed partial class CardEffect : Luban.BeanBase
{
    public CardEffect(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CardId = _buf.ReadInt();
        CardId_Ref = null;
        Kind = (card.EffectKind)_buf.ReadInt();
        TriggerTiming = (card.EffectTriggerTiming)_buf.ReadInt();
        Value = _buf.ReadInt();
        Duration = _buf.ReadInt();
        Comment = _buf.ReadString();
    }

    public static CardEffect DeserializeCardEffect(ByteBuf _buf)
    {
        return new card.CardEffect(_buf);
    }

    /// <summary>
    /// 效果标识
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 卡牌标识
    /// </summary>
    public readonly int CardId;
    public card.Card CardId_Ref;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly card.EffectKind Kind;
    /// <summary>
    /// 触发时机
    /// </summary>
    public readonly card.EffectTriggerTiming TriggerTiming;
    /// <summary>
    /// 效果数值
    /// </summary>
    public readonly int Value;
    /// <summary>
    /// 持续回合
    /// </summary>
    public readonly int Duration;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = -761230721;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        CardId_Ref = tables.TbCard.GetOrDefault(CardId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "cardId:" + CardId + ","
        + "kind:" + Kind + ","
        + "triggerTiming:" + TriggerTiming + ","
        + "value:" + Value + ","
        + "duration:" + Duration + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

