
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.card
{ 
    public enum EffectTriggerTiming
    {
        /// <summary>
        /// 释放时立即结算
        /// </summary>
        Immediate = 1,
        /// <summary>
        /// 敌人回合开始结算
        /// </summary>
        EnemyTurnStart = 2,
        /// <summary>
        /// 敌人回合结束结算
        /// </summary>
        EnemyTurnEnd = 3,
    }

} 

