
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.card
{ 
    public enum EffectKind
    {
        /// <summary>
        /// 即时伤害
        /// </summary>
        Damage = 1,
        /// <summary>
        /// 护甲增加
        /// </summary>
        Shield = 2,
        /// <summary>
        /// 回合开始扣血的持续伤害
        /// </summary>
        DamageDot = 3,
        /// <summary>
        /// 施法者能量增加
        /// </summary>
        EnergyGain = 4,
    }

} 

