
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.card
{ 
    public enum OwnerKind
    {
        /// <summary>
        /// 玩家归属
        /// </summary>
        Player = 1,
        /// <summary>
        /// 怪物归属
        /// </summary>
        Monster = 2,
        /// <summary>
        /// 两者皆可使用
        /// </summary>
        Both = 3,
    }

} 

