
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.card
{ 
    public enum TargetMode
    {
        /// <summary>
        /// 自动选择第一个存活敌方
        /// </summary>
        SingleAuto = 1,
        /// <summary>
        /// 由调用方传入指定目标
        /// </summary>
        SingleManual = 2,
        /// <summary>
        /// 全部存活敌方
        /// </summary>
        All = 3,
        /// <summary>
        /// 全部存活敌方-Damage 平均分配
        /// </summary>
        SplitAcrossAll = 4,
        /// <summary>
        /// 施法者自身
        /// </summary>
        Self = 5,
    }

} 

