
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.card
{
/// <summary>
/// 基础卡牌配置表
/// </summary>
public partial class TbCard
{
    private readonly System.Collections.Generic.Dictionary<int, card.Card> _dataMap;
    private readonly System.Collections.Generic.List<card.Card> _dataList;
    
    public TbCard(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, card.Card>(n);
        _dataList = new System.Collections.Generic.List<card.Card>(n);
        for(int i = n ; i > 0 ; --i)
        {
            card.Card _v;
            _v = global::GameConfig.card.Card.DeserializeCard(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, card.Card> DataMap => _dataMap;
    public System.Collections.Generic.List<card.Card> DataList => _dataList;

    public card.Card GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public card.Card Get(int key) => _dataMap[key];
    public card.Card this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

