
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.card
{
/// <summary>
/// 卡牌效果配置表
/// </summary>
public partial class TbCardEffect
{
    private readonly System.Collections.Generic.Dictionary<int, card.CardEffect> _dataMap;
    private readonly System.Collections.Generic.List<card.CardEffect> _dataList;
    
    public TbCardEffect(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, card.CardEffect>(n);
        _dataList = new System.Collections.Generic.List<card.CardEffect>(n);
        for(int i = n ; i > 0 ; --i)
        {
            card.CardEffect _v;
            _v = global::GameConfig.card.CardEffect.DeserializeCardEffect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, card.CardEffect> DataMap => _dataMap;
    public System.Collections.Generic.List<card.CardEffect> DataList => _dataList;

    public card.CardEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public card.CardEffect Get(int key) => _dataMap[key];
    public card.CardEffect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

