
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class BattleWaveSpawn : Luban.BeanBase
{
    public BattleWaveSpawn(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n0 = _buf.ReadSize(); BatchIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BatchIds.Add(_e0);}}
    }

    public static BattleWaveSpawn DeserializeBattleWaveSpawn(ByteBuf _buf)
    {
        return new battle.BattleWaveSpawn(_buf);
    }

    /// <summary>
    /// 刷怪方案标识
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 刷怪方案名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 刷怪方案描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 刷怪批次标识列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> BatchIds;
    public System.Collections.Generic.List<battle.BattleWaveSpawnBatch> BatchIds_Ref;
   
    public const int __ID__ = 137754836;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BatchIds_Ref = new System.Collections.Generic.List<battle.BattleWaveSpawnBatch>();
        foreach (var _v in BatchIds) { BatchIds_Ref.Add(tables.TbBattleWaveSpawnBatch.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "batchIds:" + Luban.StringUtil.CollectionToString(BatchIds) + ","
        + "}";
    }
}
}

