
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class BattleWaveSpawnBatch : Luban.BeanBase
{
    public BattleWaveSpawnBatch(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SpawnId = _buf.ReadInt();
        SpawnId_Ref = null;
        Order = _buf.ReadInt();
        MonsterId = _buf.ReadInt();
        MonsterId_Ref = null;
        Count = _buf.ReadInt();
    }

    public static BattleWaveSpawnBatch DeserializeBattleWaveSpawnBatch(ByteBuf _buf)
    {
        return new battle.BattleWaveSpawnBatch(_buf);
    }

    /// <summary>
    /// 批次标识
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属刷怪方案标识
    /// </summary>
    public readonly int SpawnId;
    public battle.BattleWaveSpawn SpawnId_Ref;
    /// <summary>
    /// 批次顺序
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 怪物标识
    /// </summary>
    public readonly int MonsterId;
    public monster.Monster MonsterId_Ref;
    /// <summary>
    /// 怪物数量
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = 1884836550;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SpawnId_Ref = tables.TbBattleWaveSpawn.GetOrDefault(SpawnId);
        MonsterId_Ref = tables.TbMonster.GetOrDefault(MonsterId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "spawnId:" + SpawnId + ","
        + "order:" + Order + ","
        + "monsterId:" + MonsterId + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

