
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 战斗波次刷怪批次表
/// </summary>
public partial class TbBattleWaveSpawnBatch
{
    private readonly System.Collections.Generic.Dictionary<string, battle.BattleWaveSpawnBatch> _dataMap;
    private readonly System.Collections.Generic.List<battle.BattleWaveSpawnBatch> _dataList;
    
    public TbBattleWaveSpawnBatch(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, battle.BattleWaveSpawnBatch>(n);
        _dataList = new System.Collections.Generic.List<battle.BattleWaveSpawnBatch>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.BattleWaveSpawnBatch _v;
            _v = global::GameConfig.battle.BattleWaveSpawnBatch.DeserializeBattleWaveSpawnBatch(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, battle.BattleWaveSpawnBatch> DataMap => _dataMap;
    public System.Collections.Generic.List<battle.BattleWaveSpawnBatch> DataList => _dataList;

    public battle.BattleWaveSpawnBatch GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.BattleWaveSpawnBatch Get(string key) => _dataMap[key];
    public battle.BattleWaveSpawnBatch this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

