
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
/// <summary>
/// 战斗波次刷怪方案表
/// </summary>
public partial class TbBattleWaveSpawn
{
    private readonly System.Collections.Generic.Dictionary<int, battle.BattleWaveSpawn> _dataMap;
    private readonly System.Collections.Generic.List<battle.BattleWaveSpawn> _dataList;
    
    public TbBattleWaveSpawn(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.BattleWaveSpawn>(n);
        _dataList = new System.Collections.Generic.List<battle.BattleWaveSpawn>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.BattleWaveSpawn _v;
            _v = global::GameConfig.battle.BattleWaveSpawn.DeserializeBattleWaveSpawn(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, battle.BattleWaveSpawn> DataMap => _dataMap;
    public System.Collections.Generic.List<battle.BattleWaveSpawn> DataList => _dataList;

    public battle.BattleWaveSpawn GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.BattleWaveSpawn Get(int key) => _dataMap[key];
    public battle.BattleWaveSpawn this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

