
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.player
{
public sealed partial class PlayerLevel : Luban.BeanBase
{
    public PlayerLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        RequiredExp = _buf.ReadInt();
        BaseEnergy = _buf.ReadInt();
        HandLimit = _buf.ReadInt();
    }

    public static PlayerLevel DeserializePlayerLevel(ByteBuf _buf)
    {
        return new player.PlayerLevel(_buf);
    }

    /// <summary>
    /// 角色等级
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 升级所需累计经验
    /// </summary>
    public readonly int RequiredExp;
    /// <summary>
    /// 基础能量
    /// </summary>
    public readonly int BaseEnergy;
    /// <summary>
    /// 手牌上限
    /// </summary>
    public readonly int HandLimit;
   
    public const int __ID__ = 818439542;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "requiredExp:" + RequiredExp + ","
        + "baseEnergy:" + BaseEnergy + ","
        + "handLimit:" + HandLimit + ","
        + "}";
    }
}
}

