
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.player
{
/// <summary>
/// 角色等级配置表
/// </summary>
public partial class TbPlayerLevel
{
    private readonly System.Collections.Generic.Dictionary<int, player.PlayerLevel> _dataMap;
    private readonly System.Collections.Generic.List<player.PlayerLevel> _dataList;
    
    public TbPlayerLevel(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, player.PlayerLevel>(n);
        _dataList = new System.Collections.Generic.List<player.PlayerLevel>(n);
        for(int i = n ; i > 0 ; --i)
        {
            player.PlayerLevel _v;
            _v = global::GameConfig.player.PlayerLevel.DeserializePlayerLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, player.PlayerLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<player.PlayerLevel> DataList => _dataList;

    public player.PlayerLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public player.PlayerLevel Get(int key) => _dataMap[key];
    public player.PlayerLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

