
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    /// <summary>
    /// 关卡主表
    /// </summary>
    public level.TbLevel TbLevel {get; }
    /// <summary>
    /// 关卡波次表
    /// </summary>
    public level.TbLevelWave TbLevelWave {get; }
    /// <summary>
    /// 怪物配置表
    /// </summary>
    public monster.TbMonster TbMonster {get; }
    /// <summary>
    /// 战斗波次刷怪方案表
    /// </summary>
    public battle.TbBattleWaveSpawn TbBattleWaveSpawn {get; }
    /// <summary>
    /// 战斗波次刷怪批次表
    /// </summary>
    public battle.TbBattleWaveSpawnBatch TbBattleWaveSpawnBatch {get; }
    /// <summary>
    /// 角色等级配置表
    /// </summary>
    public player.TbPlayerLevel TbPlayerLevel {get; }
    /// <summary>
    /// 基础卡牌配置表
    /// </summary>
    public card.TbCard TbCard {get; }
    /// <summary>
    /// 怪物牌组配置表
    /// </summary>
    public monster.TbMonsterDeck TbMonsterDeck {get; }
    /// <summary>
    /// 卡牌效果配置表
    /// </summary>
    public card.TbCardEffect TbCardEffect {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbLevel = new level.TbLevel(loader("level_tblevel"));
        TbLevelWave = new level.TbLevelWave(loader("level_tblevelwave"));
        TbMonster = new monster.TbMonster(loader("monster_tbmonster"));
        TbBattleWaveSpawn = new battle.TbBattleWaveSpawn(loader("battle_tbbattlewavespawn"));
        TbBattleWaveSpawnBatch = new battle.TbBattleWaveSpawnBatch(loader("battle_tbbattlewavespawnbatch"));
        TbPlayerLevel = new player.TbPlayerLevel(loader("player_tbplayerlevel"));
        TbCard = new card.TbCard(loader("card_tbcard"));
        TbMonsterDeck = new monster.TbMonsterDeck(loader("monster_tbmonsterdeck"));
        TbCardEffect = new card.TbCardEffect(loader("card_tbcardeffect"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbLevel.ResolveRef(this);
        TbLevelWave.ResolveRef(this);
        TbMonster.ResolveRef(this);
        TbBattleWaveSpawn.ResolveRef(this);
        TbBattleWaveSpawnBatch.ResolveRef(this);
        TbPlayerLevel.ResolveRef(this);
        TbCard.ResolveRef(this);
        TbMonsterDeck.ResolveRef(this);
        TbCardEffect.ResolveRef(this);
    }
}

}
