using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EF.Editor.EventCodeGen
{
    /// <summary>
    /// 根据扫描到的事件类型列表生成 EventHub partial 类的源代码。
    /// </summary>
    public static class EventCodeGenGenerator
    {
        /// <summary>
        /// 生成 EventHub 类的源代码。
        /// </summary>
        /// <param name="eventTypes">所有 [EventArgs] 标记的事件类型。</param>
        /// <returns>生成的 C# 源代码字符串。</returns>
        public static string Generate(List<System.Type> eventTypes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// 此文件由 EF Event Code Gen 自动生成，请勿手动修改。");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using EF.Common;");
            sb.AppendLine("using EF.Event;");
            sb.AppendLine();
            sb.AppendLine("namespace GameLogic");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 事件系统中心枢纽，管理所有类型化事件 Channel 的生命周期。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public sealed partial class EventHub : AEFManager, IEventChannelScheduler");
            sb.AppendLine("    {");

            var sorted = eventTypes.OrderBy(t => t.FullName).ToList();

            sb.AppendLine("        private readonly List<IEventChannel> _activeChannels = new List<IEventChannel>();");
            sb.AppendLine("        private readonly Dictionary<IEventChannel, int> _activeChannelIndices = new Dictionary<IEventChannel, int>();");
            sb.AppendLine();

            // 字段声明与属性访问器
            foreach (var type in sorted)
            {
                var name = type.Name;
                var fieldName = GetFieldName(name);
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// {name} 事件 Channel。");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        private EventChannel<{GetFullTypeName(type)}> {fieldName};");
                sb.AppendLine();
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// {name} 事件 Channel。");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public EventChannel<{GetFullTypeName(type)}> {name} => {fieldName} ??= CreateChannel<{GetFullTypeName(type)}>();");
                sb.AppendLine();
            }

            sb.AppendLine("        private EventChannel<T> CreateChannel<T>() where T : struct");
            sb.AppendLine("        {");
            sb.AppendLine("            return new EventChannel<T>(this);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        void IEventChannelScheduler.OnChannelActivated(IEventChannel channel)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_activeChannelIndices.ContainsKey(channel))");
            sb.AppendLine("            {");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            _activeChannelIndices[channel] = _activeChannels.Count;");
            sb.AppendLine("            _activeChannels.Add(channel);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        void IEventChannelScheduler.OnChannelBecameIdle(IEventChannel channel)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!_activeChannelIndices.TryGetValue(channel, out int index))");
            sb.AppendLine("            {");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            int lastIndex = _activeChannels.Count - 1;");
            sb.AppendLine("            IEventChannel lastChannel = _activeChannels[lastIndex];");
            sb.AppendLine();
            sb.AppendLine("            _activeChannels[index] = lastChannel;");
            sb.AppendLine("            _activeChannelIndices[lastChannel] = index;");
            sb.AppendLine();
            sb.AppendLine("            _activeChannels.RemoveAt(lastIndex);");
            sb.AppendLine("            _activeChannelIndices.Remove(channel);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Update
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 每帧驱动所有 Channel 的异步队列刷新。");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public override void Update(float elapseSeconds, float realElapseSeconds)");
            sb.AppendLine("        {");
            sb.AppendLine("            while (_activeChannels.Count > 0)");
            sb.AppendLine("            {");
            sb.AppendLine("                _activeChannels[_activeChannels.Count - 1].Flush();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Shutdown
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 关闭事件系统并清空所有 Channel。");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public override void Shutdown()");
            sb.AppendLine("        {");
            foreach (var type in sorted)
            {
                sb.AppendLine($"            ClearCreatedChannel({GetFieldName(type.Name)});");
            }
            sb.AppendLine();
            sb.AppendLine("            _activeChannels.Clear();");
            sb.AppendLine("            _activeChannelIndices.Clear();");
            sb.AppendLine("        }");

            // GetAllChannelInfos
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 获取所有 Channel 的调试信息，供 Editor 面板使用。");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public IEventChannelInfo[] GetAllChannelInfos()");
            sb.AppendLine("        {");
            sb.AppendLine("            return new IEventChannelInfo[]");
            sb.AppendLine("            {");
            foreach (var type in sorted)
            {
                sb.AppendLine($"                GetChannelInfo(\"{type.Name}\", {GetFieldName(type.Name)}),");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static void ClearCreatedChannel(IEventChannel channel)");
            sb.AppendLine("        {");
            sb.AppendLine("            channel?.Clear();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static IEventChannelInfo GetChannelInfo(string eventName, IEventChannelInfo channelInfo)");
            sb.AppendLine("        {");
            sb.AppendLine("            return channelInfo ?? new EventChannelInfoSnapshot(eventName, 0, 0, EventChannelLifecycleState.Uninitialized);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GetFullTypeName(System.Type type)
        {
            if (type.Namespace != null && type.Namespace != "GameLogic")
                return $"{type.Namespace}.{type.Name}";
            return type.Name;
        }

        private static string GetFieldName(string propertyName)
        {
            if (string.IsNullOrEmpty(propertyName))
            {
                return "_channel";
            }

            if (propertyName.Length == 1)
            {
                return "_" + char.ToLowerInvariant(propertyName[0]);
            }

            return "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
        }
    }
}
